/**
 * ElementPlus组件
 */
export enum ElComponents {
    /** 警告框 */
    ALERT = 'el-alert',
    /** 栅格间隔 */
    ASIDE = 'el-aside',
    /** 输入建议 */
    AUTOCOMPLETE = 'el-autocomplete',
    /** 头像 */
    AVATAR = 'el-avatar',
    /** 返回顶部 */
    BACKTOP = 'el-backtop',
    /** 标记 */
    BADGE = 'el-badge',
    /** 面包屑 */
    BREADCRUMB = 'el-breadcrumb',
    /** 面包屑项 */
    BREADCRUMB_ITEM = 'el-breadcrumb-item',
    /** 按钮 */
    BUTTON = 'el-button',
    /** 按钮组 */
    BUTTON_GROUP = 'el-button-group',
    /** 卡片 */
    CARD = 'el-card',
    /** 走马灯 */
    CAROUSEL = 'el-carousel',
    /** 走马灯项 */
    CAROUSEL_ITEM = 'el-carousel-item',
    /** 级联动画 */
    CASCADE_TRANSITION = 'el-cascade-transition',
    /** 多选框 */
    CHECKBOX = 'el-checkbox',
    /** 多选框按钮 */
    CHECKBOX_BUTTON = 'el-checkbox-button',
    /** 多选框组 */
    CHECKBOX_GROUP = 'el-checkbox-group',
    /** 栅格列 */
    COL = 'el-col',
    /** 折叠面板 */
    COLLAPSE = 'el-collapse',
    /** 折叠面板项 */
    COLLAPSE_ITEM = 'el-collapse-item',
    /** 颜色选择器 */
    COLOR_PICKER = 'el-color-picker',
    /** 确认框 */
    CONFIRM = 'el-confirm',
    /** 布局容器 */
    CONTAINER = 'el-container',
    /** 日期选择器 */
    DATE_PICKER = 'el-date-picker',
    /** 对话框 */
    DIALOG = 'el-dialog',
    /** 分割线 */
    DIVIDER = 'el-divider',
    /** 抽屉 */
    DRAWER = 'el-drawer',
    /** 下拉菜单 */
    DROPDOWN = 'el-dropdown',
    /** 下拉菜单项 */
    DROPDOWN_ITEM = 'el-dropdown-item',
    /** 下拉菜单菜单 */
    DROPDOWN_MENU = 'el-dropdown-menu',
    /** 空状态 */
    EMPTY = 'el-empty',
    /** 底部 */
    FOOTER = 'el-footer',
    /** 表单 */
    FORM = 'el-form',
    /** 表单项 */
    FORM_ITEM = 'el-form-item',
    /** 头部 */
    HEADER = 'el-header',
    /** 图标 */
    ICON = 'el-icon',
    /** 图片 */
    IMAGE = 'el-image',
    /** 图片预览 */
    IMAGE_VIEWER = 'el-image-viewer',
    /** 输入框 */
    INPUT = 'el-input',
    /** 计数器 */
    INPUT_NUMBER = 'el-input-number',
    /** 布局 */
    LAYOUT = 'el-layout',
    /** 主区域 */
    MAIN = 'el-main',
    /** 菜单 */
    MENU = 'el-menu',
    /** 菜单组 */
    MENU_GROUP = 'el-menu-group',
    /** 菜单项 */
    MENU_ITEM = 'el-menu-item',
    /** 菜单子项 */
    MENU_SUB = 'el-menu-sub',
    /** 消息 */
    MESSAGE = 'el-message',
    /** 模态框 */
    MODAL = 'el-modal',
    /** 通知 */
    NOTIFICATION = 'el-notification',
    /** 选择器项 */
    OPTION = 'el-option',
    /** 选择器项组 */
    OPTION_GROUP = 'el-option-group',
    /** 分页头 */
    PAGE_HEADER = 'el-page-header',
    /** 分页 */
    PAGINATION = 'el-pagination',
    /** 气泡确认框 */
    POP_CONFIRM = 'el-popconfirm',
    /** 弹出框 */
    POPOVER = 'el-popover',
    /** 气泡选择器 */
    POP_SELECT = 'el-pop-select',
    /** 进度条 */
    PROGRESS = 'el-progress',
    /** 单选框 */
    RADIO = 'el-radio',
    /** 单选框按钮 */
    RADIO_BUTTON = 'el-radio-button',
    /** 单选框组 */
    RADIO_GROUP = 'el-radio-group',
    /** 评分 */
    RATE = 'el-rate',
    /** 栅格行 */
    ROW = 'el-row',
    /** 滚动条 */
    SCROLLBAR = 'el-scrollbar',
    /** 选择器 */
    SELECT = 'el-select',
    /** 骨架屏 */
    SKELETON = 'el-skeleton',
    /** 滑块 */
    SLIDER = 'el-slider',
    /** 空间 */
    SPACE = 'el-space',
    /** 加载中 */
    SPINNER = 'el-spinner',
    /** 步骤条 */
    STEPPER = 'el-stepper',
    /** 步骤条项 */
    STEPPER_ITEM = 'el-stepper-item',
    /** 粘性布局 */
    STICKY = 'el-sticky',
    /** 子菜单 */
    SUBMENU = 'el-submenu',
    /** 开关 */
    SWITCH = 'el-switch',
    /** 标签页面板 */
    TAB_PANE = 'el-tab-pane',
    /** 表格 */
    TABLE = 'el-table',
    /** 表格列 */
    TABLE_COLUMN = 'el-table-column',
    /** 标签页 */
    TABS = 'el-tabs',
    /** 标签 */
    TAG = 'el-tag',
    /** 时间选择器 */
    TIME_PICKER = 'el-time-picker',
    /** 时间选择器 */
    TIME_SELECT = 'el-time-select',
    /** 时间线 */
    TIMELINE = 'el-timeline',
    /** 时间线项 */
    TIMELINE_ITEM = 'el-timeline-item',
    /** 消息提示 */
    TOAST = 'el-toast',
    /** 提示框 */
    TOOLTIP = 'el-tooltip',
    /** 穿梭框 */
    TRANSFER = 'el-transfer',
    /** 动画 */
    TRANSTION = 'el-transition',
    /** 树形控件 */
    TREE = 'el-tree',
    /** 上传 */
    UPLOAD = 'el-upload'
}
